
name: main

on:
  push:
    branches: [ "master", "devel" ]
  pull_request:
    branches: [ "master", "devel" ]

jobs:
  quicktest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3 python3-pip

      - name: Update packaging
        run: pip3 install --upgrade pip

      - name: Run build
        run: pip3 install .[test]

      - name: Run tests and collect coverage
        run: pytest -v -m "not slow" --cov=./src

  installtest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3 python3-pip

      - name: Update packaging
        run: pip3 install --upgrade pip

      - name: Run build
        run: pip3 install .

      - name: Seek help
        run: python -m bogoslav.main --help

  typechecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3 python3-pip

      - name: Update packaging
        run: pip3 install --upgrade pip

      - name: Run build
        run: pip3 install .[test,dev]

      - name: Run typechecker
        run: mypy

